name: get-data

on:
  workflow_dispatch:
  schedule:
  - cron: '5 4 */7 * *'


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}

      - uses: ruby/setup-ruby@v1

      - name: Install and update data
        run: |
          make install
          make run

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: New publications data
