name: update-data

on:
  workflow_dispatch:
  schedule:
  - cron: '0 6 * * *'


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.6'

      - name: Install and update data
        run: |
          make install
          make update-data

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: New publications data
