name: update-data
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.6'

      - name: Install and update data
        run: make install
        run: make update-data

      - name: Commit changes
        run: |
          git commit publicacoes_periodicas.csv publicacoes_periodicas.json -m 'New publications data' || echo "No changes to commit"
          git push https://${{github.actor}}:${{secrets.GH_TOKEN}}@github.com/${{github.repository}}.git HEAD:${{ github.ref }} || echo "No changes to commit"
